name: Build
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: Build action
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: make build