name: Release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'A type of version bump'
        default: 'major'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: make build

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: ${{ github.event.inputs.version_bump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

